apiVersion: v2
name: frontend
description: Next.js Frontend Helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - nextjs
  - frontend
  - react
  - javascript

maintainers:
  - name: Your Name
    email: your.email@example.com

home: https://github.com/your-username/your-repo
sources:
  - https://github.com/your-username/your-repo/tree/main/apps/frontend