replicaCount: 5

image:
  repository: ghcr.io/GITHUB_USERNAME/REPO_NAME/frontend
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: ghcr-pull-secret

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: "default-frontend-ratelimit@kubernetescrd,default-frontend-cors@kubernetescrd,default-frontend-body-size@kubernetescrd"
  hosts:
    - host: app.yourcompany.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-prod-tls
      hosts:
        - app.yourcompany.com

env:
  - name: NODE_ENV
    value: "production"
  - name: NEXT_PUBLIC_API_URL
    value: "https://api.yourcompany.com"
  - name: NEXT_TELEMETRY_DISABLED
    value: "1"
