replicaCount: 5

image:
  repository: monorepocontainerregistry.azurecr.io/frontend
  pullPolicy: Always
  tag: latest

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/rate-limit: "200"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: app.yourcompany.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-prod-tls
      hosts:
        - app.yourcompany.com

env:
  - name: NODE_ENV
    value: "production"
  - name: NEXT_PUBLIC_API_URL
    value: "https://api.yourcompany.com"
  - name: NEXT_TELEMETRY_DISABLED
    value: "1"