{{- if .Values.scheduler.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "laravel-api.fullname" . }}-scheduler
  labels:
    {{- include "laravel-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  schedule: {{ .Values.scheduler.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "laravel-api.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: scheduler
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "laravel-api.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          
          containers:
            - name: scheduler
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                {{- toYaml .Values.scheduler.command | nindent 16 }}
              env:
                {{- include "laravel-api.env" . | nindent 16 }}
                {{- with .Values.scheduler.env }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ include "laravel-api.fullname" . }}
                - secretRef:
                    name: {{ include "laravel-api.fullname" . }}
              resources:
                {{- toYaml .Values.scheduler.resources | nindent 16 }}
          
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}