{{- if .Values.scheduler.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "api.fullname" . }}-scheduler
  labels:
    {{- include "api.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  schedule: {{ .Values.scheduler.schedule | quote }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "api.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: scheduler
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "api.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: scheduler
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["php", "artisan", "schedule:run"]
              env:
                {{- toYaml .Values.env | nindent 16 }}
              resources:
                {{- if .Values.scheduler.resources }}
                {{- toYaml .Values.scheduler.resources | nindent 16 }}
                {{- else }}
                {{- toYaml .Values.resources | nindent 16 }}
                {{- end }}
          restartPolicy: OnFailure
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}