apiVersion: v2
name: api
description: Laravel API application using Larakube
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: larakube
    version: 0.2.4
    repository: https://charts.larakube.com
    alias: laravel-app
  - name: redis
    version: 17.15.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
