replicaCount: 2

image:
  repository: ghcr.io/GITHUB_USERNAME/REPO_NAME/api
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: ghcr-pull-secret

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    traefik.ingress.kubernetes.io/router.middlewares: "default-api-headers@kubernetescrd,default-api-body-size@kubernetescrd"
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-tls
      hosts:
        - api.example.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
pdb:
  maxUnavailable: 1

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables
env:
  - name: APP_ENV
    value: "production"
  - name: APP_DEBUG
    value: "false"
  - name: DB_CONNECTION
    value: "pgsql"
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: api-secrets
        key: db-host
  - name: DB_DATABASE
    valueFrom:
      secretKeyRef:
        name: api-secrets
        key: db-database
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: api-secrets
        key: db-username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: api-secrets
        key: db-password
  - name: REDIS_HOST
    value: "api-redis-master"
  - name: REDIS_PORT
    value: "6379"

# Secrets (these should be managed externally in production)
secrets:
  db-host: "api-postgresql"
  db-database: "laravel"
  db-username: "laravel"
  db-password: "changeme"
  app-key: "base64:changeme"

# Dependencies
redis:
  enabled: true
  auth:
    enabled: false

postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    database: "laravel"
    username: "laravel"
    password: "changeme"
  primary:
    persistence:
      enabled: true
      size: 20Gi

# Queue configuration
queue:
  enabled: true
  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Scheduler configuration
scheduler:
  enabled: true
  schedule: "* * * * *"  # Every minute
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Database migration configuration
databaseMigration:
  enabled: true
  retry: 3
