replicaCount: 5

image:
  repository: ghcr.io/GITHUB_USERNAME/REPO_NAME/api
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: ghcr-pull-secret

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: "default-api-ratelimit@kubernetescrd,default-api-headers@kubernetescrd,default-api-body-size@kubernetescrd"
  hosts:
    - host: api.yourcompany.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wildcard-yourcompany-com-tls
      hosts:
        - api.yourcompany.com

env:
  - name: APP_ENV
    value: "production"
  - name: APP_DEBUG
    value: "false"
  - name: LOG_LEVEL
    value: "warning"
  - name: DB_CONNECTION
    value: "mysql"
  - name: CACHE_DRIVER
    value: "redis"
  - name: SESSION_DRIVER
    value: "redis"
  - name: QUEUE_CONNECTION
    value: "redis"

# External MySQL (Azure Database for MySQL)
mysql:
  enabled: false

redis:
  enabled: true
  auth:
    enabled: true
    password: "prod-redis-password"
  master:
    persistence:
      enabled: true
      size: 8Gi
  replica:
    replicaCount: 2
    persistence:
      enabled: true
      size: 8Gi

# Production secrets (use Azure Key Vault in real scenarios)
secrets:
  db-host: "prod-mysql.mysql.database.azure.com"
  db-database: "laravel_prod"
  db-username: "laravel_prod"
  db-password: "production-db-password"
  app-key: "base64:production-app-key"
  jwt-secret: "production-jwt-secret"
