name: Frontend

on:
  push:
    branches: [main, develop]
    paths: ["apps/frontend/**", "infrastructure/helm/frontend/**"]
  pull_request:
    branches: [main]
    paths: ["apps/frontend/**", "infrastructure/helm/frontend/**"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: apps/frontend/package-lock.json
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          cd apps/frontend
          npm ci

      - name: Run linting
        run: |
          cd apps/frontend
          npm run lint

      - name: Run type checking
        run: |
          cd apps/frontend
          npm run type-check

      - name: Run unit tests
        run: |
          cd apps/frontend
          npm run test -- --coverage --watchAll=false
        env:
          CI: true

      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        with:
          file: apps/frontend/coverage/lcov.info
          flags: frontend
          name: frontend-coverage
        continue-on-error: true

      - name: Run build test
        run: |
          cd apps/frontend
          npm run build
        env:
          NEXT_PUBLIC_API_URL: "http://localhost:3001"

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd apps/frontend
          npm ci

      - name: Run npm audit
        run: |
          cd apps/frontend
          npm audit --audit-level high
        continue-on-error: true

      - name: ESLint security scan
        run: |
          cd apps/frontend
          npx eslint . --ext .js,.jsx,.ts,.tsx --format json --output-file eslint-results.json || true
        continue-on-error: true

      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'apps/frontend'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  build-and-push:
    needs: [test, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v4

      - name: Set environment
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "NAMESPACE=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "NAMESPACE=staging" >> $GITHUB_ENV
          fi

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group monorepo-rg --name monorepo-aks

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy to AKS
        run: |
          helm upgrade --install frontend-${{ env.ENVIRONMENT }} \
            ./infrastructure/helm/frontend \
            --namespace ${{ env.NAMESPACE }} \
            --create-namespace \
            --values ./infrastructure/helm/frontend/values.yaml \
            $(if [ "${{ env.ENVIRONMENT }}" = "production" ]; then echo "--values ./infrastructure/helm/frontend/values-production.yaml"; fi) \
            --set image.tag=${{ github.sha }} \
            --timeout=10m \
            --wait

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/frontend-${{ env.ENVIRONMENT }} -n ${{ env.NAMESPACE }} --timeout=300s
          kubectl get pods -n ${{ env.NAMESPACE }} -l app.kubernetes.io/name=frontend

      - name: Run smoke tests
        run: |
          # Wait for service to be ready
          sleep 30
          # Get service URL and test basic functionality
          kubectl get ingress -n ${{ env.NAMESPACE }}
          # Add actual smoke test commands here
        continue-on-error: true